when:
  - event: push
    branch: main

steps:
  - name: build-image
    image: woodpeckerci/plugin-kaniko
    settings:
      registry: gitea.ewpt3ch.dev
      repo: ewpt3ch/resume
      tags: 
        - latest
        - ${CI_COMMIT_SHA:0:8}
      dockerfile: Dockerfile
      context: .
      username:
        from_secret: gitea_username
      password:
        from_secret: gitea_password
      cache: true
      cache_repo: ewpt3ch/resume-cache

  - name: build-docs
    image: gitea.ewpt3ch.dev/ewpt3ch/resume:latest
    pull: true
    commands:
      - python src/main.py
      - cp publish/resume.* /

  - name: deploy
    image: appleboy/drone-scp
    settings:
      host: ewpt3ch.dev
      username: httpcd
      key:
        from_secret: ssh_deploy_key
      port: 25213
      target: /home/httpcd/resume/
      source: ./resume.*
      strip_components: 1
      rm: false
